### PR TITLE
Links for the get involved section

### PR DESCRIPTION
**Pull request by kafitzgerald**
The new website looks great :tada:!

This PR just adds a few links to the "Get Involved" section to make it a little easier to navigate.

### CODE REVIEW

**Comment by kafitzgerald** [comment]
I'm still getting familiar with MkDocs, but it looks like the failure might be because of the existing reference to 'archive/index.html' rather than anything in the PR itself.  

I did noticed that when I click the "[Legacy Site Archive](https://ucar-sea.github.io/sea-website/archive/index.html)" link on the "About Us" page it throws a 404 error.  Maybe the same thing?  

Here's the output from the log:
```
  mkdocs build --strict
  shell: /usr/bin/bash -el {0}
  env:
    INPUT_RUN_POST: true
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/sea-website/sea-website/site
WARNING -  A reference to 'archive/index.html' is included in the 'nav' configuration, which is not found in the documentation files.

Aborted with 1 warnings in strict mode!
Error: Process completed with exit code 1.
```

**Comment by negin513** [comment]
This looks great to me. I am taking a look at the error.

**Comment by vanderwb** [comment]
I wouldn't worry too much about that failed test - I didn't really think it was ready for CI testing of PRs yet, but will be by the launch.

The archive part of it needs to get filled in. It's in there for a reminder to me to talk to Jeff Alipit to figure that part out.

Thanks for the super fast review and contribution!

**Comment by negin513** [comment]
Sounds good! I just tested it and made sure that the fail is indeed triggered by the missing page. 

When I updated the page to link the sea website, the test now works. PR #2 does not need to be merged for now but is more of a placeholder that the build does not have any issues. 

@vanderwb : we can make a dummy 404 page in place for the archive as the placeholder so that the build does not fail, but that is just an option.

**Pull request merged**
